require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IteratedFunctionSystemsController, type: :controller do
  login

  # This should return the minimal set of attributes required to create a valid
  # IteratedFunctionSystem. As you add validations to IteratedFunctionSystem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    #skip("Add a hash of attributes valid for your model")
    {name: 'LSD'}
  }

  let(:invalid_attributes) {
    #skip("Add a hash of attributes invalid for your model")
    {name: "Глебпарад"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IteratedFunctionSystemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all iterated_function_systems as @ifss" do
      iterated_function_system = create :ifs, user: @user
      get :index, {}, valid_session
      expect(assigns(:ifss)).to eq([iterated_function_system])
    end
  end

  describe "GET #show" do
    it "assigns the requested iterated_function_system as @ifs" do
      iterated_function_system = create :ifs
      get :show, {:id => iterated_function_system.to_param}, valid_session
      expect(assigns(:ifs)).to eq(iterated_function_system)
    end
  end

  describe "GET #new" do
    it "assigns a new iterated_function_system as @ifs" do
      get :new, {}, valid_session
      expect(assigns(:ifs)).to be_a_new(IteratedFunctionSystem)
    end
  end

  describe "GET #edit" do
    it "assigns the requested iterated_function_system as @iterated_function_system" do
      iterated_function_system = create :ifs, user: @user
      get :edit, {:id => iterated_function_system.to_param}, valid_session
      expect(assigns(:iterated_function_system)).to eq(iterated_function_system)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new IteratedFunctionSystem" do
        expect {
          post :create, {:iterated_function_system => valid_attributes}, valid_session
        }.to change(IteratedFunctionSystem, :count).by(1)
      end

      it "assigns a newly created iterated_function_system as @iterated_function_system" do
        post :create, {:iterated_function_system => valid_attributes}, valid_session
        expect(assigns(:iterated_function_system)).to be_a(IteratedFunctionSystem)
        expect(assigns(:iterated_function_system)).to be_persisted
      end

      it "redirects to the created iterated_function_system" do
        post :create, {:iterated_function_system => valid_attributes}, valid_session
        expect(response).to redirect_to(IteratedFunctionSystem.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved iterated_function_system as @iterated_function_system" do
        post :create, {:iterated_function_system => invalid_attributes}, valid_session
        expect(assigns(:iterated_function_system)).to be_a_new(IteratedFunctionSystem)
      end

      it "re-renders the 'new' template" do
        post :create, {:iterated_function_system => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    before(:each) { @ifs =  create :ifs, user: @user  }
    context "with valid params" do
      let(:new_attributes) {
        {name: "Holocoust"}
      }

      it "updates the requested iterated_function_system" do
        put :update, {id: @ifs.to_param, iterated_function_system: new_attributes}, valid_session
        @ifs.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested iterated_function_system as @iterated_function_system" do
        put :update, {id: @ifs.to_param, :iterated_function_system => valid_attributes}, valid_session
        expect(assigns(:iterated_function_system)).to eq(@ifs)
      end

      it "redirects to the iterated_function_system" do
        @ifs
        put :update, {:id => @ifs.to_param, :iterated_function_system => valid_attributes}, valid_session
        expect(response).to redirect_to(@ifs)
      end
    end

    context "with invalid params" do
      it "assigns the iterated_function_system as @iterated_function_system" do
        put :update, {id: @ifs.to_param, :iterated_function_system => invalid_attributes}, valid_session
        expect(assigns(:iterated_function_system)).to eq(@ifs)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => @ifs.to_param, :iterated_function_system => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    before(:each) do
      @ifs =  create :ifs, user: @user
      @not_my_ifs = create :ifs, user: create(:user)
      @request.env['HTTP_REFERER'] = "/iterated_function_systems"
    end
    it "destroys the requested iterated_function_system" do
      expect {
        delete :destroy, {id: @ifs.to_param}, valid_session
      }.to change(IteratedFunctionSystem, :count).by(-1)
    end

    it "redirects to the iterated_function_systems list" do
      delete :destroy, {id: @ifs.to_param}, valid_session
      expect(response).to redirect_to(iterated_function_systems_url)
    end
  end

end
